2018-10-31T20:48:25.874-0500 I CONTROL  [initandlisten] MongoDB starting : pid=24559 port=27017 dbpath=/data/db 64-bit host=installadmins-MacBook-Pro-5.local
2018-10-31T20:48:25.874-0500 I CONTROL  [initandlisten] db version v4.0.0
2018-10-31T20:48:25.874-0500 I CONTROL  [initandlisten] git version: 3b07af3d4f471ae89e8186d33bbb1d5259597d51
2018-10-31T20:48:25.875-0500 I CONTROL  [initandlisten] allocator: system
2018-10-31T20:48:25.875-0500 I CONTROL  [initandlisten] modules: none
2018-10-31T20:48:25.875-0500 I CONTROL  [initandlisten] build environment:
2018-10-31T20:48:25.875-0500 I CONTROL  [initandlisten]     distarch: x86_64
2018-10-31T20:48:25.875-0500 I CONTROL  [initandlisten]     target_arch: x86_64
2018-10-31T20:48:25.875-0500 I CONTROL  [initandlisten] options: { processManagement: { fork: true }, systemLog: { destination: "file", path: "../../bash/vocab/mongo_log/mongod.log" } }
2018-10-31T20:48:25.877-0500 I STORAGE  [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2018-10-31T20:48:25.877-0500 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7680M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2018-10-31T20:48:26.843-0500 I STORAGE  [initandlisten] WiredTiger message [1541036906:843914][24559:0x7fffc357d3c0], txn-recover: Main recovery loop: starting at 100/20096
2018-10-31T20:48:26.938-0500 I STORAGE  [initandlisten] WiredTiger message [1541036906:938184][24559:0x7fffc357d3c0], txn-recover: Recovering log 100 through 101
2018-10-31T20:48:27.000-0500 I STORAGE  [initandlisten] WiredTiger message [1541036907:619][24559:0x7fffc357d3c0], txn-recover: Recovering log 101 through 101
2018-10-31T20:48:27.045-0500 I STORAGE  [initandlisten] WiredTiger message [1541036907:45792][24559:0x7fffc357d3c0], txn-recover: Set global recovery timestamp: 0
2018-10-31T20:48:27.169-0500 I RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
2018-10-31T20:48:27.604-0500 I CONTROL  [initandlisten] 
2018-10-31T20:48:27.604-0500 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2018-10-31T20:48:27.604-0500 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2018-10-31T20:48:27.604-0500 I CONTROL  [initandlisten] 
2018-10-31T20:48:27.605-0500 I CONTROL  [initandlisten] ** WARNING: This server is bound to localhost.
2018-10-31T20:48:27.605-0500 I CONTROL  [initandlisten] **          Remote systems will be unable to connect to this server. 
2018-10-31T20:48:27.605-0500 I CONTROL  [initandlisten] **          Start the server with --bind_ip <address> to specify which IP 
2018-10-31T20:48:27.605-0500 I CONTROL  [initandlisten] **          addresses it should serve responses from, or with --bind_ip_all to
2018-10-31T20:48:27.606-0500 I CONTROL  [initandlisten] **          bind to all interfaces. If this behavior is desired, start the
2018-10-31T20:48:27.606-0500 I CONTROL  [initandlisten] **          server with --bind_ip 127.0.0.1 to disable this warning.
2018-10-31T20:48:27.606-0500 I CONTROL  [initandlisten] 
2018-10-31T20:48:27.764-0500 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2018-10-31T20:48:27.766-0500 I NETWORK  [initandlisten] waiting for connections on port 27017
2018-10-31T20:48:28.811-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:60946 #1 (1 connection now open)
2018-10-31T20:48:28.812-0500 I NETWORK  [conn1] received client metadata from 127.0.0.1:60946 conn1: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.12.5" }, platform: "CPython 3.6.3.final.0" }
2018-10-31T20:48:29.400-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:60947 #2 (2 connections now open)
2018-10-31T20:48:29.401-0500 I NETWORK  [conn2] received client metadata from 127.0.0.1:60947 conn2: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.12.5" }, platform: "CPython 3.6.3.final.0" }
2018-10-31T20:49:34.267-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:60966 #3 (3 connections now open)
2018-10-31T20:49:34.268-0500 I NETWORK  [conn3] received client metadata from 127.0.0.1:60966 conn3: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.12.5" }, platform: "CPython 3.6.3.final.0" }
2018-10-31T20:55:22.760-0500 I NETWORK  [conn3] end connection 127.0.0.1:60966 (2 connections now open)
2018-10-31T20:55:22.760-0500 I NETWORK  [conn2] end connection 127.0.0.1:60947 (1 connection now open)
2018-10-31T20:55:23.238-0500 I NETWORK  [conn1] end connection 127.0.0.1:60946 (0 connections now open)
2018-10-31T20:55:23.330-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:61003 #4 (1 connection now open)
2018-10-31T20:55:23.332-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:61005 #5 (2 connections now open)
2018-10-31T20:55:23.335-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:61007 #6 (3 connections now open)
2018-10-31T20:55:23.338-0500 I NETWORK  [conn4] end connection 127.0.0.1:61003 (2 connections now open)
2018-10-31T20:55:23.338-0500 I NETWORK  [conn5] end connection 127.0.0.1:61005 (1 connection now open)
2018-10-31T20:55:23.338-0500 I NETWORK  [conn6] end connection 127.0.0.1:61007 (0 connections now open)
2018-10-31T20:55:23.357-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:61011 #7 (1 connection now open)
2018-10-31T20:55:23.358-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:61013 #8 (2 connections now open)
2018-10-31T20:55:23.361-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:61015 #9 (3 connections now open)
2018-10-31T20:55:23.364-0500 I NETWORK  [conn7] end connection 127.0.0.1:61011 (2 connections now open)
2018-10-31T20:55:23.364-0500 I NETWORK  [conn8] end connection 127.0.0.1:61013 (1 connection now open)
2018-10-31T20:55:23.364-0500 I NETWORK  [conn9] end connection 127.0.0.1:61015 (0 connections now open)
2018-10-31T20:55:23.382-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:61019 #10 (1 connection now open)
2018-10-31T20:55:23.383-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:61021 #11 (2 connections now open)
2018-10-31T20:55:23.385-0500 I NETWORK  [conn10] end connection 127.0.0.1:61019 (1 connection now open)
2018-10-31T20:55:23.385-0500 I NETWORK  [conn11] end connection 127.0.0.1:61021 (0 connections now open)
2018-10-31T20:55:23.682-0500 I CONTROL  [signalProcessingThread] got signal 15 (Terminated: 15), will terminate after current cmd ends
2018-10-31T20:55:23.682-0500 I NETWORK  [signalProcessingThread] shutdown: going to close listening sockets...
2018-10-31T20:55:23.682-0500 I NETWORK  [signalProcessingThread] removing socket file: /tmp/mongodb-27017.sock
2018-10-31T20:55:23.683-0500 I CONTROL  [signalProcessingThread] Shutting down free monitoring
2018-10-31T20:55:23.683-0500 I FTDC     [signalProcessingThread] Shutting down full-time diagnostic data capture
2018-10-31T20:55:23.685-0500 I STORAGE  [signalProcessingThread] WiredTigerKVEngine shutting down
2018-10-31T20:55:23.896-0500 I STORAGE  [signalProcessingThread] shutdown: removing fs lock...
2018-10-31T20:55:23.897-0500 I CONTROL  [signalProcessingThread] now exiting
2018-10-31T20:55:23.897-0500 I CONTROL  [signalProcessingThread] shutting down with code:0
