2018-10-31T20:55:41.807-0500 I CONTROL  [initandlisten] MongoDB starting : pid=24637 port=27017 dbpath=/data/db 64-bit host=installminsMBP5
2018-10-31T20:55:41.807-0500 I CONTROL  [initandlisten] db version v4.0.0
2018-10-31T20:55:41.807-0500 I CONTROL  [initandlisten] git version: 3b07af3d4f471ae89e8186d33bbb1d5259597d51
2018-10-31T20:55:41.807-0500 I CONTROL  [initandlisten] allocator: system
2018-10-31T20:55:41.807-0500 I CONTROL  [initandlisten] modules: none
2018-10-31T20:55:41.808-0500 I CONTROL  [initandlisten] build environment:
2018-10-31T20:55:41.808-0500 I CONTROL  [initandlisten]     distarch: x86_64
2018-10-31T20:55:41.808-0500 I CONTROL  [initandlisten]     target_arch: x86_64
2018-10-31T20:55:41.808-0500 I CONTROL  [initandlisten] options: { processManagement: { fork: true }, systemLog: { destination: "file", path: "../../bash/vocab/mongo_log/mongod.log" } }
2018-10-31T20:55:41.808-0500 I STORAGE  [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2018-10-31T20:55:41.809-0500 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7680M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2018-10-31T20:55:42.713-0500 I STORAGE  [initandlisten] WiredTiger message [1541037342:713932][24637:0x7fffc357d3c0], txn-recover: Main recovery loop: starting at 101/16384
2018-10-31T20:55:42.800-0500 I STORAGE  [initandlisten] WiredTiger message [1541037342:800604][24637:0x7fffc357d3c0], txn-recover: Recovering log 101 through 102
2018-10-31T20:55:42.859-0500 I STORAGE  [initandlisten] WiredTiger message [1541037342:859379][24637:0x7fffc357d3c0], txn-recover: Recovering log 102 through 102
2018-10-31T20:55:42.906-0500 I STORAGE  [initandlisten] WiredTiger message [1541037342:906239][24637:0x7fffc357d3c0], txn-recover: Set global recovery timestamp: 0
2018-10-31T20:55:43.044-0500 I RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
2018-10-31T20:55:43.462-0500 I CONTROL  [initandlisten] 
2018-10-31T20:55:43.462-0500 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2018-10-31T20:55:43.462-0500 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2018-10-31T20:55:43.463-0500 I CONTROL  [initandlisten] 
2018-10-31T20:55:43.465-0500 I CONTROL  [initandlisten] ** WARNING: This server is bound to localhost.
2018-10-31T20:55:43.465-0500 I CONTROL  [initandlisten] **          Remote systems will be unable to connect to this server. 
2018-10-31T20:55:43.466-0500 I CONTROL  [initandlisten] **          Start the server with --bind_ip <address> to specify which IP 
2018-10-31T20:55:43.466-0500 I CONTROL  [initandlisten] **          addresses it should serve responses from, or with --bind_ip_all to
2018-10-31T20:55:43.467-0500 I CONTROL  [initandlisten] **          bind to all interfaces. If this behavior is desired, start the
2018-10-31T20:55:43.467-0500 I CONTROL  [initandlisten] **          server with --bind_ip 127.0.0.1 to disable this warning.
2018-10-31T20:55:43.468-0500 I CONTROL  [initandlisten] 
2018-10-31T20:55:43.622-0500 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2018-10-31T20:55:43.623-0500 I NETWORK  [initandlisten] waiting for connections on port 27017
2018-10-31T20:55:44.385-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:61036 #1 (1 connection now open)
2018-10-31T20:55:44.385-0500 I NETWORK  [conn1] received client metadata from 127.0.0.1:61036 conn1: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.12.5" }, platform: "CPython 3.6.3.final.0" }
2018-10-31T20:55:44.964-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:61040 #2 (2 connections now open)
2018-10-31T20:55:44.965-0500 I NETWORK  [conn2] received client metadata from 127.0.0.1:61040 conn2: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.12.5" }, platform: "CPython 3.6.3.final.0" }
2018-10-31T20:55:54.481-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:61050 #3 (3 connections now open)
2018-10-31T20:55:54.481-0500 I NETWORK  [conn3] received client metadata from 127.0.0.1:61050 conn3: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.12.5" }, platform: "CPython 3.6.3.final.0" }
2018-10-31T20:57:26.810-0500 I NETWORK  [conn3] end connection 127.0.0.1:61050 (2 connections now open)
2018-10-31T20:57:26.810-0500 I NETWORK  [conn2] end connection 127.0.0.1:61040 (1 connection now open)
2018-10-31T20:57:27.026-0500 I NETWORK  [conn1] end connection 127.0.0.1:61036 (0 connections now open)
2018-10-31T20:57:27.082-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:61064 #4 (1 connection now open)
2018-10-31T20:57:27.084-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:61066 #5 (2 connections now open)
2018-10-31T20:57:27.086-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:61068 #6 (3 connections now open)
2018-10-31T20:57:27.087-0500 I NETWORK  [conn4] end connection 127.0.0.1:61064 (2 connections now open)
2018-10-31T20:57:27.087-0500 I NETWORK  [conn5] end connection 127.0.0.1:61066 (1 connection now open)
2018-10-31T20:57:27.087-0500 I NETWORK  [conn6] end connection 127.0.0.1:61068 (0 connections now open)
2018-10-31T20:57:27.106-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:61072 #7 (1 connection now open)
2018-10-31T20:57:27.107-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:61074 #8 (2 connections now open)
2018-10-31T20:57:27.110-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:61076 #9 (3 connections now open)
2018-10-31T20:57:27.111-0500 I NETWORK  [conn7] end connection 127.0.0.1:61072 (2 connections now open)
2018-10-31T20:57:27.111-0500 I NETWORK  [conn8] end connection 127.0.0.1:61074 (1 connection now open)
2018-10-31T20:57:27.111-0500 I NETWORK  [conn9] end connection 127.0.0.1:61076 (0 connections now open)
2018-10-31T20:57:27.129-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:61080 #10 (1 connection now open)
2018-10-31T20:57:27.131-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:61082 #11 (2 connections now open)
2018-10-31T20:57:27.133-0500 I NETWORK  [conn11] end connection 127.0.0.1:61082 (0 connections now open)
2018-10-31T20:57:27.133-0500 I NETWORK  [conn10] end connection 127.0.0.1:61080 (1 connection now open)
2018-10-31T20:57:31.094-0500 I CONTROL  [signalProcessingThread] got signal 15 (Terminated: 15), will terminate after current cmd ends
2018-10-31T20:57:31.094-0500 I NETWORK  [signalProcessingThread] shutdown: going to close listening sockets...
2018-10-31T20:57:31.094-0500 I NETWORK  [signalProcessingThread] removing socket file: /tmp/mongodb-27017.sock
2018-10-31T20:57:31.095-0500 I CONTROL  [signalProcessingThread] Shutting down free monitoring
2018-10-31T20:57:31.095-0500 I FTDC     [signalProcessingThread] Shutting down full-time diagnostic data capture
2018-10-31T20:57:31.097-0500 I STORAGE  [signalProcessingThread] WiredTigerKVEngine shutting down
2018-10-31T20:57:31.231-0500 I STORAGE  [signalProcessingThread] shutdown: removing fs lock...
2018-10-31T20:57:31.232-0500 I CONTROL  [signalProcessingThread] now exiting
2018-10-31T20:57:31.232-0500 I CONTROL  [signalProcessingThread] shutting down with code:0
