2018-07-25T10:57:15.852-0500 I CONTROL  [initandlisten] MongoDB starting : pid=15673 port=27017 dbpath=/data/db 64-bit host=installadmins-MacBook-Pro-5.local
2018-07-25T10:57:15.852-0500 I CONTROL  [initandlisten] db version v4.0.0
2018-07-25T10:57:15.853-0500 I CONTROL  [initandlisten] git version: 3b07af3d4f471ae89e8186d33bbb1d5259597d51
2018-07-25T10:57:15.853-0500 I CONTROL  [initandlisten] allocator: system
2018-07-25T10:57:15.853-0500 I CONTROL  [initandlisten] modules: none
2018-07-25T10:57:15.853-0500 I CONTROL  [initandlisten] build environment:
2018-07-25T10:57:15.853-0500 I CONTROL  [initandlisten]     distarch: x86_64
2018-07-25T10:57:15.853-0500 I CONTROL  [initandlisten]     target_arch: x86_64
2018-07-25T10:57:15.853-0500 I CONTROL  [initandlisten] options: { processManagement: { fork: true }, systemLog: { destination: "file", path: "../../bash/vocab/mongo_log/mongod.log" } }
2018-07-25T10:57:15.854-0500 I STORAGE  [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2018-07-25T10:57:15.854-0500 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7680M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2018-07-25T10:57:16.776-0500 I STORAGE  [initandlisten] WiredTiger message [1532534236:776113][15673:0x7fffb42423c0], txn-recover: Main recovery loop: starting at 6/7552
2018-07-25T10:57:16.875-0500 I STORAGE  [initandlisten] WiredTiger message [1532534236:875742][15673:0x7fffb42423c0], txn-recover: Recovering log 6 through 7
2018-07-25T10:57:16.969-0500 I STORAGE  [initandlisten] WiredTiger message [1532534236:969651][15673:0x7fffb42423c0], txn-recover: Recovering log 7 through 7
2018-07-25T10:57:17.028-0500 I STORAGE  [initandlisten] WiredTiger message [1532534237:28847][15673:0x7fffb42423c0], txn-recover: Set global recovery timestamp: 0
2018-07-25T10:57:17.132-0500 I RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
2018-07-25T10:57:17.320-0500 I CONTROL  [initandlisten] 
2018-07-25T10:57:17.321-0500 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2018-07-25T10:57:17.321-0500 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2018-07-25T10:57:17.321-0500 I CONTROL  [initandlisten] 
2018-07-25T10:57:17.322-0500 I CONTROL  [initandlisten] ** WARNING: This server is bound to localhost.
2018-07-25T10:57:17.322-0500 I CONTROL  [initandlisten] **          Remote systems will be unable to connect to this server. 
2018-07-25T10:57:17.322-0500 I CONTROL  [initandlisten] **          Start the server with --bind_ip <address> to specify which IP 
2018-07-25T10:57:17.323-0500 I CONTROL  [initandlisten] **          addresses it should serve responses from, or with --bind_ip_all to
2018-07-25T10:57:17.323-0500 I CONTROL  [initandlisten] **          bind to all interfaces. If this behavior is desired, start the
2018-07-25T10:57:17.323-0500 I CONTROL  [initandlisten] **          server with --bind_ip 127.0.0.1 to disable this warning.
2018-07-25T10:57:17.324-0500 I CONTROL  [initandlisten] 
2018-07-25T10:57:17.496-0500 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2018-07-25T10:57:17.497-0500 I NETWORK  [initandlisten] waiting for connections on port 27017
2018-07-25T10:57:18.208-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:60256 #1 (1 connection now open)
2018-07-25T10:57:18.209-0500 I NETWORK  [conn1] received client metadata from 127.0.0.1:60256 conn1: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.12.5" }, platform: "CPython 3.6.3.final.0" }
2018-07-25T10:57:18.210-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:60257 #2 (2 connections now open)
2018-07-25T10:57:18.210-0500 I NETWORK  [conn2] received client metadata from 127.0.0.1:60257 conn2: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.12.5" }, platform: "CPython 3.6.3.final.0" }
2018-07-25T10:57:18.211-0500 I COMMAND  [conn2] dropDatabase vocab - starting
2018-07-25T10:57:18.211-0500 I COMMAND  [conn2] dropDatabase vocab - dropping 0 collections
2018-07-25T10:57:18.261-0500 I COMMAND  [conn2] dropDatabase vocab - finished
2018-07-25T10:57:19.004-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:60258 #3 (3 connections now open)
2018-07-25T10:57:19.004-0500 I NETWORK  [conn3] received client metadata from 127.0.0.1:60258 conn3: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.12.5" }, platform: "CPython 3.6.3.final.0" }
2018-07-25T10:57:19.005-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:60259 #4 (4 connections now open)
2018-07-25T10:57:19.006-0500 I NETWORK  [conn4] received client metadata from 127.0.0.1:60259 conn4: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.12.5" }, platform: "CPython 3.6.3.final.0" }
2018-07-25T10:57:39.400-0500 I STORAGE  [conn4] createCollection: vocab.Practice with generated UUID: 55dd5182-d0a1-43b4-b25e-7d54883a2aa1
2018-07-25T10:57:53.840-0500 I STORAGE  [conn4] createCollection: vocab.Quiz with generated UUID: eaca7c51-334d-4c64-9a0f-b956741bc396
2018-07-25T10:58:11.099-0500 I NETWORK  [conn4] end connection 127.0.0.1:60259 (3 connections now open)
2018-07-25T10:58:11.099-0500 I NETWORK  [conn3] end connection 127.0.0.1:60258 (2 connections now open)
2018-07-25T10:58:11.599-0500 I NETWORK  [conn2] end connection 127.0.0.1:60257 (1 connection now open)
2018-07-25T10:58:11.599-0500 I NETWORK  [conn1] end connection 127.0.0.1:60256 (0 connections now open)
