2018-10-02T17:47:39.918-0500 I CONTROL  [initandlisten] MongoDB starting : pid=22563 port=27017 dbpath=/data/db 64-bit host=installminsMBP5
2018-10-02T17:47:39.918-0500 I CONTROL  [initandlisten] db version v4.0.0
2018-10-02T17:47:39.918-0500 I CONTROL  [initandlisten] git version: 3b07af3d4f471ae89e8186d33bbb1d5259597d51
2018-10-02T17:47:39.918-0500 I CONTROL  [initandlisten] allocator: system
2018-10-02T17:47:39.918-0500 I CONTROL  [initandlisten] modules: none
2018-10-02T17:47:39.919-0500 I CONTROL  [initandlisten] build environment:
2018-10-02T17:47:39.919-0500 I CONTROL  [initandlisten]     distarch: x86_64
2018-10-02T17:47:39.919-0500 I CONTROL  [initandlisten]     target_arch: x86_64
2018-10-02T17:47:39.919-0500 I CONTROL  [initandlisten] options: { processManagement: { fork: true }, systemLog: { destination: "file", path: "../../bash/vocab/mongo_log/mongod.log" } }
2018-10-02T17:47:39.920-0500 I STORAGE  [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2018-10-02T17:47:39.920-0500 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7680M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2018-10-02T17:47:40.812-0500 I STORAGE  [initandlisten] WiredTiger message [1538520460:812049][22563:0x7fffc99ae3c0], txn-recover: Main recovery loop: starting at 62/10880
2018-10-02T17:47:40.909-0500 I STORAGE  [initandlisten] WiredTiger message [1538520460:909011][22563:0x7fffc99ae3c0], txn-recover: Recovering log 62 through 63
2018-10-02T17:47:40.982-0500 I STORAGE  [initandlisten] WiredTiger message [1538520460:982247][22563:0x7fffc99ae3c0], txn-recover: Recovering log 63 through 63
2018-10-02T17:47:41.039-0500 I STORAGE  [initandlisten] WiredTiger message [1538520461:39065][22563:0x7fffc99ae3c0], txn-recover: Set global recovery timestamp: 0
2018-10-02T17:47:41.149-0500 I RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
2018-10-02T17:47:41.458-0500 I CONTROL  [initandlisten] 
2018-10-02T17:47:41.459-0500 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2018-10-02T17:47:41.460-0500 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2018-10-02T17:47:41.460-0500 I CONTROL  [initandlisten] 
2018-10-02T17:47:41.461-0500 I CONTROL  [initandlisten] ** WARNING: This server is bound to localhost.
2018-10-02T17:47:41.461-0500 I CONTROL  [initandlisten] **          Remote systems will be unable to connect to this server. 
2018-10-02T17:47:41.462-0500 I CONTROL  [initandlisten] **          Start the server with --bind_ip <address> to specify which IP 
2018-10-02T17:47:41.462-0500 I CONTROL  [initandlisten] **          addresses it should serve responses from, or with --bind_ip_all to
2018-10-02T17:47:41.463-0500 I CONTROL  [initandlisten] **          bind to all interfaces. If this behavior is desired, start the
2018-10-02T17:47:41.464-0500 I CONTROL  [initandlisten] **          server with --bind_ip 127.0.0.1 to disable this warning.
2018-10-02T17:47:41.464-0500 I CONTROL  [initandlisten] 
2018-10-02T17:47:41.650-0500 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2018-10-02T17:47:41.651-0500 I NETWORK  [initandlisten] waiting for connections on port 27017
2018-10-02T17:47:42.316-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:53561 #1 (1 connection now open)
2018-10-02T17:47:42.317-0500 I NETWORK  [conn1] received client metadata from 127.0.0.1:53561 conn1: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.12.5" }, platform: "CPython 3.6.3.final.0" }
2018-10-02T17:47:42.844-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:53566 #2 (2 connections now open)
2018-10-02T17:47:42.845-0500 I NETWORK  [conn2] received client metadata from 127.0.0.1:53566 conn2: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.12.5" }, platform: "CPython 3.6.3.final.0" }
2018-10-02T17:49:03.553-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:53897 #3 (3 connections now open)
2018-10-02T17:49:03.554-0500 I NETWORK  [conn3] received client metadata from 127.0.0.1:53897 conn3: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.12.5" }, platform: "CPython 3.6.3.final.0" }
2018-10-02T17:53:46.527-0500 I NETWORK  [conn3] end connection 127.0.0.1:53897 (2 connections now open)
2018-10-02T17:53:46.527-0500 I NETWORK  [conn2] end connection 127.0.0.1:53566 (1 connection now open)
2018-10-02T17:53:46.836-0500 I NETWORK  [conn1] end connection 127.0.0.1:53561 (0 connections now open)
2018-10-02T17:53:46.890-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:55050 #4 (1 connection now open)
2018-10-02T17:53:46.891-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:55052 #5 (2 connections now open)
2018-10-02T17:53:46.894-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:55054 #6 (3 connections now open)
2018-10-02T17:53:46.895-0500 I NETWORK  [conn5] end connection 127.0.0.1:55052 (1 connection now open)
2018-10-02T17:53:46.895-0500 I NETWORK  [conn4] end connection 127.0.0.1:55050 (2 connections now open)
2018-10-02T17:53:46.895-0500 I NETWORK  [conn6] end connection 127.0.0.1:55054 (0 connections now open)
2018-10-02T17:53:46.913-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:55058 #7 (1 connection now open)
2018-10-02T17:53:46.915-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:55060 #8 (2 connections now open)
2018-10-02T17:53:46.918-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:55062 #9 (3 connections now open)
2018-10-02T17:53:46.919-0500 I NETWORK  [conn7] end connection 127.0.0.1:55058 (2 connections now open)
2018-10-02T17:53:46.919-0500 I NETWORK  [conn8] end connection 127.0.0.1:55060 (1 connection now open)
2018-10-02T17:53:46.919-0500 I NETWORK  [conn9] end connection 127.0.0.1:55062 (0 connections now open)
2018-10-02T17:53:46.939-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:55066 #10 (1 connection now open)
2018-10-02T17:53:46.940-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:55068 #11 (2 connections now open)
2018-10-02T17:53:46.942-0500 I NETWORK  [conn10] end connection 127.0.0.1:55066 (1 connection now open)
2018-10-02T17:53:46.942-0500 I NETWORK  [conn11] end connection 127.0.0.1:55068 (0 connections now open)
2018-10-02T17:53:50.088-0500 I CONTROL  [signalProcessingThread] got signal 15 (Terminated: 15), will terminate after current cmd ends
2018-10-02T17:53:50.089-0500 I NETWORK  [signalProcessingThread] shutdown: going to close listening sockets...
2018-10-02T17:53:50.089-0500 I NETWORK  [signalProcessingThread] removing socket file: /tmp/mongodb-27017.sock
2018-10-02T17:53:50.089-0500 I CONTROL  [signalProcessingThread] Shutting down free monitoring
2018-10-02T17:53:50.090-0500 I FTDC     [signalProcessingThread] Shutting down full-time diagnostic data capture
2018-10-02T17:53:50.091-0500 I STORAGE  [signalProcessingThread] WiredTigerKVEngine shutting down
2018-10-02T17:53:50.234-0500 I STORAGE  [signalProcessingThread] shutdown: removing fs lock...
2018-10-02T17:53:50.236-0500 I CONTROL  [signalProcessingThread] now exiting
2018-10-02T17:53:50.237-0500 I CONTROL  [signalProcessingThread] shutting down with code:0
