2018-10-30T20:44:10.097-0500 I CONTROL  [initandlisten] MongoDB starting : pid=19259 port=27017 dbpath=/data/db 64-bit host=installminsMBP5
2018-10-30T20:44:10.097-0500 I CONTROL  [initandlisten] db version v4.0.0
2018-10-30T20:44:10.097-0500 I CONTROL  [initandlisten] git version: 3b07af3d4f471ae89e8186d33bbb1d5259597d51
2018-10-30T20:44:10.097-0500 I CONTROL  [initandlisten] allocator: system
2018-10-30T20:44:10.097-0500 I CONTROL  [initandlisten] modules: none
2018-10-30T20:44:10.098-0500 I CONTROL  [initandlisten] build environment:
2018-10-30T20:44:10.098-0500 I CONTROL  [initandlisten]     distarch: x86_64
2018-10-30T20:44:10.098-0500 I CONTROL  [initandlisten]     target_arch: x86_64
2018-10-30T20:44:10.098-0500 I CONTROL  [initandlisten] options: { processManagement: { fork: true }, systemLog: { destination: "file", path: "../../bash/vocab/mongo_log/mongod.log" } }
2018-10-30T20:44:10.099-0500 I STORAGE  [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2018-10-30T20:44:10.100-0500 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7680M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2018-10-30T20:44:11.018-0500 I STORAGE  [initandlisten] WiredTiger message [1540950251:18099][19259:0x7fffc357d3c0], txn-recover: Main recovery loop: starting at 98/19968
2018-10-30T20:44:11.114-0500 I STORAGE  [initandlisten] WiredTiger message [1540950251:114811][19259:0x7fffc357d3c0], txn-recover: Recovering log 98 through 99
2018-10-30T20:44:11.187-0500 I STORAGE  [initandlisten] WiredTiger message [1540950251:187103][19259:0x7fffc357d3c0], txn-recover: Recovering log 99 through 99
2018-10-30T20:44:11.235-0500 I STORAGE  [initandlisten] WiredTiger message [1540950251:235518][19259:0x7fffc357d3c0], txn-recover: Set global recovery timestamp: 0
2018-10-30T20:44:11.351-0500 I RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
2018-10-30T20:44:11.680-0500 I CONTROL  [initandlisten] 
2018-10-30T20:44:11.680-0500 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2018-10-30T20:44:11.681-0500 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2018-10-30T20:44:11.681-0500 I CONTROL  [initandlisten] 
2018-10-30T20:44:11.681-0500 I CONTROL  [initandlisten] ** WARNING: This server is bound to localhost.
2018-10-30T20:44:11.681-0500 I CONTROL  [initandlisten] **          Remote systems will be unable to connect to this server. 
2018-10-30T20:44:11.681-0500 I CONTROL  [initandlisten] **          Start the server with --bind_ip <address> to specify which IP 
2018-10-30T20:44:11.682-0500 I CONTROL  [initandlisten] **          addresses it should serve responses from, or with --bind_ip_all to
2018-10-30T20:44:11.682-0500 I CONTROL  [initandlisten] **          bind to all interfaces. If this behavior is desired, start the
2018-10-30T20:44:11.682-0500 I CONTROL  [initandlisten] **          server with --bind_ip 127.0.0.1 to disable this warning.
2018-10-30T20:44:11.682-0500 I CONTROL  [initandlisten] 
2018-10-30T20:44:11.839-0500 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2018-10-30T20:44:11.842-0500 I NETWORK  [initandlisten] waiting for connections on port 27017
2018-10-30T20:44:12.936-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:58694 #1 (1 connection now open)
2018-10-30T20:44:12.937-0500 I NETWORK  [conn1] received client metadata from 127.0.0.1:58694 conn1: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.12.5" }, platform: "CPython 3.6.3.final.0" }
2018-10-30T20:44:13.488-0500 I NETWORK  [conn1] end connection 127.0.0.1:58694 (0 connections now open)
2018-10-30T20:44:13.491-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:58695 #2 (1 connection now open)
2018-10-30T20:44:13.492-0500 I NETWORK  [conn2] received client metadata from 127.0.0.1:58695 conn2: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.12.5" }, platform: "CPython 3.6.3.final.0" }
2018-10-30T20:44:13.525-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:58696 #3 (2 connections now open)
2018-10-30T20:44:13.527-0500 I NETWORK  [conn3] received client metadata from 127.0.0.1:58696 conn3: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.12.5" }, platform: "CPython 3.6.3.final.0" }
2018-10-30T20:44:13.552-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:58700 #4 (3 connections now open)
2018-10-30T20:44:13.554-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:58702 #5 (4 connections now open)
2018-10-30T20:44:13.557-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:58704 #6 (5 connections now open)
2018-10-30T20:44:13.561-0500 I NETWORK  [conn5] end connection 127.0.0.1:58702 (3 connections now open)
2018-10-30T20:44:13.561-0500 I NETWORK  [conn6] end connection 127.0.0.1:58704 (2 connections now open)
2018-10-30T20:44:13.561-0500 I NETWORK  [conn4] end connection 127.0.0.1:58700 (4 connections now open)
2018-10-30T20:44:13.579-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:58708 #7 (3 connections now open)
2018-10-30T20:44:13.581-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:58710 #8 (4 connections now open)
2018-10-30T20:44:13.584-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:58712 #9 (5 connections now open)
2018-10-30T20:44:13.586-0500 I NETWORK  [conn7] end connection 127.0.0.1:58708 (4 connections now open)
2018-10-30T20:44:13.586-0500 I NETWORK  [conn8] end connection 127.0.0.1:58710 (3 connections now open)
2018-10-30T20:44:13.586-0500 I NETWORK  [conn9] end connection 127.0.0.1:58712 (2 connections now open)
2018-10-30T20:44:13.606-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:58716 #10 (3 connections now open)
2018-10-30T20:44:13.607-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:58718 #11 (4 connections now open)
2018-10-30T20:44:13.610-0500 I NETWORK  [conn10] end connection 127.0.0.1:58716 (3 connections now open)
2018-10-30T20:44:13.610-0500 I NETWORK  [conn11] end connection 127.0.0.1:58718 (2 connections now open)
2018-10-30T20:44:16.973-0500 I CONTROL  [signalProcessingThread] got signal 15 (Terminated: 15), will terminate after current cmd ends
2018-10-30T20:44:16.973-0500 I NETWORK  [signalProcessingThread] shutdown: going to close listening sockets...
2018-10-30T20:44:16.973-0500 I NETWORK  [signalProcessingThread] removing socket file: /tmp/mongodb-27017.sock
2018-10-30T20:44:16.974-0500 I CONTROL  [signalProcessingThread] Shutting down free monitoring
2018-10-30T20:44:16.974-0500 I FTDC     [signalProcessingThread] Shutting down full-time diagnostic data capture
2018-10-30T20:44:16.975-0500 I STORAGE  [signalProcessingThread] WiredTigerKVEngine shutting down
2018-10-30T20:44:17.183-0500 I STORAGE  [signalProcessingThread] shutdown: removing fs lock...
2018-10-30T20:44:17.184-0500 I CONTROL  [signalProcessingThread] now exiting
2018-10-30T20:44:17.185-0500 I CONTROL  [signalProcessingThread] shutting down with code:0
